### ISSUE TITLE
The link between `huh` and BetterErrors is not clear in the naming.

### ISSUE THREAD

**Issue by jordwalke** [chenglou/BetterErrors#35]
I think the `huh` program should be renamed to something like `berror`.

**Comment by chenglou** [comment]
yeah that was quirky and too short. I was appending `|& huh` by hand so shorter was easier.
I guess the real-er use-case is to do it programmatically. I'll change that.

**Comment by chenglou** [comment]
Done in https://github.com/chenglou/BetterErrors/blob/bec338a3bfe6e7847c74402afe39565c345de287/package.json#L13
