### ISSUE TITLE
Don't show underline for leading white space in source examples.

### ISSUE THREAD

**Issue by jordwalke** [chenglou/BetterErrors#44]
Suppose in this example, there were an error spanning the entire `if` block. BetterErrors currently underlines (and makes red) the white space between the numbers and the text. I believe it looks much better if this is not the case.

```
 193 |             if (isMainAxisRow && isStyleDimDefined(child.contents, CSS_FLEX_DIRECTION_ROW)) {
 194 |
 195 |               /* The width is definite, so use that as the flex basis.*/
 196 |               child.contents.layout.flexBasis = fmaxf(child.contents.style.width, getPaddingAndBorderAxis(child.contents, CSS_FLEX_DIRECTION_ROW));
 197 |             } else if (not <| isMainAxisRow && isStyleDimDefined(child.contents, CSS_FLEX_DIRECTION_COLUMN)) {
 198 |
 199 |               /* The height is definite, so use that as the flex basis.*/
```

**Comment by chenglou** [comment]
How about without underline? 

After:
<img width="1280" alt="screenshot 2016-06-04 13 04 16" src="https://cloud.githubusercontent.com/assets/1909539/15799449/e2f99572-2a54-11e6-881d-b89ca66a1fd6.png">
<img width="1280" alt="screenshot 2016-06-04 13 04 24" src="https://cloud.githubusercontent.com/assets/1909539/15799450/e2fa6736-2a54-11e6-8250-4cbc4421d0e2.png">

Before:
<img width="1280" alt="screenshot 2016-06-04 13 06 05" src="https://cloud.githubusercontent.com/assets/1909539/15799456/200d753c-2a55-11e6-8882-4801edae883b.png">
<img width="1280" alt="screenshot 2016-06-04 13 06 08" src="https://cloud.githubusercontent.com/assets/1909539/15799457/20342452-2a55-11e6-931b-2c3d213e2eb1.png">
